project:
  type: website
  output-dir: dist
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!LICENSE.md"
format:
  html:
    theme:
      light: flatly
      dark: darkly
execute:
  freeze: true
website:
  title: "Codercub Summer of Code 2026"
  page-navigation: true
  sidebar:
    logo: theme/codercub.png
    style: "docked"
    collapse-level: 2
    search: true
    contents:
      - text: "Future Intelligence Lab"
        href: index.qmd
      - text: "---"
      - text: "Syllabus"
        href: labs/Syllabus.qmd
      - section: "Day 1"
        contents:
          - text: "Slides"
            href: labs/01/slides.qmd
            target: blank
      - section: "Day 2"
        contents:
          - text: "Slides"
            href: labs/02/slides.qmd
            target: blank
          - section: "Notebooks"
            contents:
              - text: "hello_world.ipynb"
                href: labs/02/notebooks/hello_world.ipynb
              - text: "air_quality.ipynb"
                href: labs/02/notebooks/air_quality.ipynb
              - text: "correlation.ipynb"
                href: labs/02/notebooks/correlation.ipynb
      - section: "Day 3"
        contents:
          - text: "Slides"
            href: labs/03/slides.qmd
            target: blank
          - section: "Notebooks"
            contents:
              - text: "finding_disasters.ipynb"
                href: labs/03/notebooks/finding_disasters.ipynb
              - text: "finding_cause.ipynb"
                href: labs/03/notebooks/finding_cause.ipynb
      - section: "Day 4"
        contents:
          - text: "Slides"
            href: labs/04/slides.qmd
            target: blank
      - section: "Day 5"
        contents:
          - text: "Slides"
            href: labs/05/slides.qmd
            target: blank
      - section: "Day 6"
        contents:
          - text: "Slides"
            href: labs/06/slides.qmd
            target: blank
      - section: "Day 7"
        contents:
          - text: "Slides"
            href: labs/07/slides.qmd
            target: blank
      - section: "Day 8"
        contents:
          - text: "Slides"
            href: labs/08/slides.qmd
            target: blank
      - section: "Day 9"
        contents:
          - text: "Slides"
            href: labs/09/slides.qmd
            target: blank
      - section: "Day 10"
        contents:
          - text: "Slides"
            href: labs/10/slides.qmd
            target: blank